language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.4"
  - "pypy3.5"
  - "pypy3.6"
install:
    - pip install -e .
    - pip install codecov pytest-cov hypothesis
script:
    - pytest --cov=squiggle
cache: pip
after_success:
    - codecov
