language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
    - pip install -e .
    - pip install codecov pytest-cov
script:
    - pytest --cov=squiggle
cache: pip
after_success:
    - codecov
