language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
install:
    - pip install -e .
    - pip install hypothesis pytest
script:
    - pytest
cache: pip
after_success:
    - codecov
